### PR TITLE
Added some Type Conversion snippets

### PR DESCRIPTION
**Pull request by Confectrician**
This is a partly implementation of #52

Please take a look at my prefixes, idk if you have som kind of convention for those.
If yes i can adapt them of course.

Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

### CODE REVIEW

**Comment by kubawolanin** [comment]
Excellent! 
@rkoshak would you mind taking a look? 
This is a direct implementation of your [Type Conversions](https://community.openhab.org/t/type-conversions/32684) article into code snippets :-)
Cheers

**Comment by Confectrician** [comment]
> This is a direct implementation of your Type Conversions article into code snippets :-)

Not at all to be honest. 😄 
I just grabbed the smaller ones, since i have to investigate some time for the bigger snippets myself.
I haven't worked yet with all of them and i want them to be correct for contributing of course.

**Comment by kubawolanin** [comment]
Thank you for your work!

**Comment by rkoshak** [comment]
I'm just noticing this. I get so many GitHub messages I tend to tuck them away and review them later. I must have accidentally did that with this. 

Here are my comments:

> Converts the item state int a string

It converts any Item state to a String, not just int so it would be better to remove the "int" part.

>  "contact to numeric": {
 +        "prefix": "contactNum",
 +        "body": "val ${1:Item}Num = if(${1:Item}.state == ON) 1 else 0",
 +        "description": "Converts a contact OpenClosedType  to its numeric equivalent"
 +    },

Should be

`"body": "val ${1:Item}Num = if(${1:Item}.state == OPEN) 1 else 0",`

> "Creates a sendCommand with prefilled RGB logic"

Might be better worded as "Calls sendCommand on a Color Item using RGB values"

> "description": "Converts a dimmer percentage value to a float"

As a float should it be divided by 100? e.g. 52% == 0.52

Looks great to me. I'm loving VSCode and I don't even have the Language Server stuff yet (I'm still on 2.2 SNAPSHOT build in the 900s, time for an upgrade).

**Comment by Confectrician** [comment]
> It converts any Item state to a String, not just int so it would be better to remove the "int" part.

That s just a typo. Should be the word `into`. Sorry

I will do a PR this week to fix all of those things.
Thanks for pointing them out.

**Pull request merged**
