### PR TITLE
Add human readable threadsleep description hover.

### LINKED ISSUE #237: Add human readable cron desciptions to the hover provider
**Describe the solution you'd like**

It would be pretty nice to recognise hovering over a cron expression in a `.rule` or `.persist` file and describe the expression in a human readable way.

**Additional context**
Possible ready to use library: https://github.com/bradymholt/cRonstrue
It is i18n ready, so also prepared for a i18n'ified extension.

### LINKED ISSUE #240: Add human readable Thread desciptions to the hover provider
Just like the feature request for cron (#237) it would be great if there was a human readable description for the `Thread.sleep()` method in rules.

So lazy people like me do not have to calculate `Thread::sleep(420000)` to `7 minutes` ourselves. 😄

### PR DESCRIPTION
**Pull request by Confectrician**
Fixes #237
Fixes #240

Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

### CODE REVIEW

**Comment by Confectrician** [comment]
@CWempe could you do some testing?

Extension with this changes included can be downloaded at our [azure artifactory](https://artprodsu6weu.artifacts.visualstudio.com/A9a899564-e2b9-49e3-bd3d-4101a64d20ed/82e39b03-2e63-4a34-84ca-3cb57be32202/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL29wZW5oYWIvcHJvamVjdElkLzgyZTM5YjAzLTJlNjMtNGEzNC04NGNhLTNjYjU3YmUzMjIwMi9idWlsZElkLzE5MS9hcnRpZmFjdE5hbWUvb3BlbmhhYi12c2NvZGU1/content?format=file&subPath=%2Fopenhab-0.8.1-pr-242-56d7ab7.vsix)

**Comment by CWempe** [comment]
I used this test commands:

```java
Thread::sleep(12345678)
Thread::sleep(1234567890)
Thread::sleep(1234567890123)
Thread::sleep(9765432)
Thread::sleep(7)
Thread::sleep(4000)
Thread::sleep(60000)
Thread::sleep(7abc)
Thread::sleep(7.)
Thread::sleep(xy7abc)
```

As expected, it does not calculate days or years. 😜 

image

And a warning would be nice if there is an invalid value inside the method.

image

And it seems there is a big blank line above "Sleep Time".

Other than that it looks great!

**Comment by Confectrician** [comment]
I have limited the matching up to 9 digit millisecond numbers.
This would theoretically allow a sleep of 11.5 days when using `999999999`.
Thinking about decreasing this to 7 digits, which would be about 2.7 hours.
This is still way longer than a sleep should be for best practice.

Also i will not do any validation (at least like "you should not mix digits and numbers") in the hover.
Validation should be done on language level and our hover provider works separate from other code validations currently.
Anyway i will try to not display anything, when some of the mixed stuff, like shown above, gets hovered.

**Comment by Confectrician** [comment]
OK this changes should prevent the hover from being shown when something different than a 1 to 7 digit number is in the thread sleep method.

Vsix is available in our [azure artifactory](https://artprodsu6weu.artifacts.visualstudio.com/A9a899564-e2b9-49e3-bd3d-4101a64d20ed/82e39b03-2e63-4a34-84ca-3cb57be32202/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL29wZW5oYWIvcHJvamVjdElkLzgyZTM5YjAzLTJlNjMtNGEzNC04NGNhLTNjYjU3YmUzMjIwMi9idWlsZElkLzE5NC9hcnRpZmFjdE5hbWUvb3BlbmhhYi12c2NvZGU1/content?format=file&subPath=%2Fopenhab-0.8.1-pr-242-889d91d.vsix)

**Comment by Confectrician** [comment]
Overall solution looks good so far.
We can still adapt smaller improvements, therefore merging already. 🙂

**Pull request merged**
