### PR TITLE
Add Update Notice

### LINKED ISSUE #249: Provide Proper Migration Documentation
While starting this in #247 i realized that it would be more sufficient to provide a proper migration logic in place for future releases.

We should:

- Add some logic to recognize when the openhab extension got installed/updated
- Check for major version changes
- Provide a WebView view with detailed instructions for the current update
- Display this migration path view
- Provide migration helpers where possible
- Store relevant extension date needed to determine this in globalstate (https://code.visualstudio.com/updates/v1_31#_global-storage-path) (https://stackoverflow.com/questions/54039837/where-to-store-global-binary-data-for-a-vscode-extension)

### PR DESCRIPTION
**Pull request by Confectrician**
Fixes #249 

Already done:

- Basic things that are needed for showing a webview
- Basic "vscode like" page design and first contents
- Check for extension updates from the openhab extension
- Provide a persistent storage for the to check version changes in the future and store data.

### CODE REVIEW

**Comment by Confectrician** [comment]
Here is a first impression of how the update page looks.

image

**Comment by Confectrician** [comment]
@CWempe maybe you can find some time to check the spelling and look of the update page.

Currently the Page will show up on each extension startup.
I am now starting with the logic to determine an extension update.

**Comment by Confectrician** [comment]
Latest change provides following behavior:

- Extension check current version in storage with the one that is activated
- If they are not the same the update notice will be shown
- Otherwise extension will startup normal
- Update notice can be re-visited with a new command "updateNotice" via `cmd` + `shift` + `p`

**Comment by CWempe** [comment]
Im am no expert in english either, but here are some thoughts:

current: `take care manually of those.`
better: `take care of those manually.`

current: `Tip: Have a look at the Latest Release information`
Maybe [the official addon discription](https://marketplace.visualstudio.com/items?itemName=openhab.openhab) would be a better place for a changelog and information about breaking changes?!
The normal user should not care about a source code management system like GitHub. 😉 
On the other hand the official description might get overloaded. 🤔 

btw: I just noticed there is a changelog tab in the marlked place:

image

current: `openhab.karafCommand | openhab.karafCommand`
Do not mention a parameter that has not been changed in the changed parameter table.
But didn't you changed it already? Maybe in another PR...

current: `you should adapt those names on your custom configuration`
better: `you should adapt those names in your configuration`
Is it `in` or `on`?
I think every configuration is a custom configuration.

Looks good so far! 👍 

I tested  `v1.0.0-pr-250-6141a3d`.

**Comment by Confectrician** [comment]
Thanks for the typo/grammar checks.
I have incorporated all off them.

>current: Tip: Have a look at the Latest Release information
Maybe the official addon discription would be a better place for a changelog and information about breaking changes?!
The normal user should not care about a source code management system like GitHub. 😉
On the other hand the official description might get overloaded. 🤔

Did you click the link for testing? Every release has a description field. 
That's where we also list changes/breaking changes for openHAB currently.

image

My idea was to provide the needed information there additionally to those small information.
It is public reachable and the link will work for every lease, so we don't have to remember to change it every time.

Here is an example from openHAB Distro with much explanations in the description.
https://github.com/openhab/openhab-distro/releases/tag/3.1.0.M2
That's what i was aiming for without too much wall of text but more than currently.

>btw: I just noticed there is a changelog tab in the marlked place:

I would have sworn that this is already filled via https://github.com/openhab/openhab-vscode/blob/main/CHANGELOG.md on default.
I will check why this is not working currently.
Reference: #252 

>current: openhab.karafCommand | openhab.karafCommand

Typo. Sorry and fixed.

**Comment by CWempe** [comment]
> Did you click the link for testing? Every release has a description field.

I did. And personally I like the release notes on GitHub.
But from a user perspective the changelog in the marketplace is more relevant, I think.

If the `CHANGELOG.md` will get updated and published to the Marketplace that would be the best solution in my opinion.

**Comment by Confectrician** [comment]
But the changelog is not meant for explanations of how to deal with breaking changes.
Basically this is just a documentation of what has changed in which way.

If we would add user descriptions, it would break the mould of its original purpose.

Btw the release notes are just a computed "mini changelog" cut out from changelog.md currently.
There is a script which is doing this in our build system.

**Comment by CWempe** [comment]
> If we would add user descriptions, it would break the mould of its original purpose.

Ok, I understand.

**Comment by Confectrician** [comment]
Anyways i think this will be a huge improvement compared to the current (more or less none) existing migration paths.
We can improve and extend this at any point when we recognize that it needs some changes.

I have some things in mind that will make it easy to add changing update instructions (or even other informational messages) into new versions with the codebase introduced here.

**Pull request merged**
