### PR TITLE
Empty Frame snippet for Sitemap

### PR DESCRIPTION
**Pull request by glebster-d**
Add snippet with empty Frame with label and icon as an option to the sitemap
Signed-off-by: Glebster-D <47859640+glebster-d@users.noreply.github.com>

### CODE REVIEW

**Comment by Confectrician** [comment]
Hey @glebster-d and thanks for your contribution.

Could you do me a favor and sign-off your first comment like described in our contribution guidelines with a `Signed-off-by: Your Name <yourmail@example.com>`?
https://github.com/openhab/openhab-vscode/blob/main/CONTRIBUTING.md#sign-your-work

Usually this has to be done for every commit (not in this PR needed, i will take care of the form) and i made exception for your first Pull Request with the telegram action as a first time contributor.

**Comment by glebster-d** [comment]
Thanks for clarifying. Can I add a sign-off comment here?

**Comment by Confectrician** [comment]
Yes of course.
You can add it to your first comment in the PR with the edit function.
I will use it for the merge then.

**Comment by glebster-d** [comment]
Thanks for the link. I will take this into account in the next commits

**Comment by Confectrician** [comment]
Thanks again for the contribution.

I will accept that for this snippet commit as is, but have to clarify a small thing again for the future.

image

A real name is mandatory usually.
I know this may seem a bit overwhelming for a snippet contribution, but we have to follow the guidelines as all other openHAB repositories do.
I have a bit of range (especially for the documentation repository), but i am forced to take care of this, when it comes to code changes.

Anyway i am glad for everyone contributing here (which is one reason for me to do some exceptions), besides me so i am available for any questions or needed help. 🙂 
So please ping me if there are any questions or if you want to help out in other extension parts too.

**Review by Confectrician — APPROVED** [review]
Thanks 👍

**Pull request merged**
