### PR TITLE
Items Explorer view - Initial contribution

### PR DESCRIPTION
**Pull request by kubawolanin**
Related to #7 

Sneak peek:
dynamic-rules

Signed-off-by: Kuba Wolanin <hi@kubawolanin.com> (kubawolanin)

### CODE REVIEW

**Comment by ThomDietrich** [comment]
This is amazing! This is already pretty close to what I was wishing for with #7 

A few comments:

* In a big installation one might not always know the exact nature of an item based in its item name. Would it be possible to include the item type and item name? The type could be depicted as an icon, both could be shown in the context menu. (if easily possible)
* The created rule receives a rather meaningless rule name. How about "React on ITEMNAME (ITEMLABEL) change/update"
* "changed from" is a condition I'm personally not using very often. How about 1-2 additional commented lines for the condition and one comment as a placeholder for the rule logic (instead of just a few spaces)

These are just a few comments on top of this great feature. Thanks @kubawolanin for working so eagerly on the extension!!


Btw. thanks for showcasing the Speedtest example :blush:

**Comment by kubawolanin** [comment]
Hey @ThomDietrich  thank you for the feedback!

I've added some icons corresponding with the item's type:
items-explorer
They are Material icons (Apache 2.0 license).

Unfortunately VS Code doesn't allow us to display SVG (or any other) icons from external source (e.g. REST api or whatever). I suspect this is due to the fact that the editor's instance is locally hosted (`file:///...`)
I've [already tried](https://github.com/openhab/openhab-vscode/pull/20/files#diff-9473c6a6e3bd54ae0d95683d0fc29754R43) to display ESH icons there with no luck.
We'll need to live with type-based icons for now ;-)

> Would it be possible to include the item type and item name? The type could be depicted as an icon, both could be shown in the context menu. (if easily possible)

I didn't include item's label here because I wanted the TreeView to be clean. People working on the Items with rules operate on item's name (and state) more often than on its label.
VSCode Tree View API doesn't allow to change the hover title yet, but that may change in the future.

> The created rule receives a rather meaningless rule name. How about "React on ITEMNAME (ITEMLABEL) change/update"

I like it! Thank you! 😃 

> "changed from" is a condition I'm personally not using very often. How about 1-2 additional commented lines for the condition and one comment as a placeholder for the rule logic (instead of just a few spaces)

That's the issue I faced when I was implementing the [code snippets](https://github.com/openhab/openhab-vscode/blob/master/snippets/openhabrules.json).

Do we really want to provide as much template as possible? Or maybe *just enough* to get the job done? 😉 

I could easily change the rule template to this:
```
rule "React on ${item.label} (${item.name}) change"
when
    Item ${item.name} changed from ` + state + `
//     Item ${item.name} changed to ` + state + `
//     Item ${item.name} received command ` + state + `
then
    // if (${item.name}.state === ` + state + `) {
    //    <your condition here>
    // }
end
```

But I think it's too crowded.
For the condition, maybe let's just choose between `received command` and `changed from|to`.
On the flip side, `command` is not always equal to `state` 🤔 

Anyways, my 3 cents. Thank you again for the feedback!

**Comment by ThomDietrich** [comment]
Hey @kubawolanin 👋 Thanks for the extensive answer!

> I've added some icons corresponding with the item's type

Looks amazing. 

> They are Material icons (Apache 2.0 license). @kaikreuzer are we good with including these?

https://eclipse.org/legal/eplfaq.php#3RDPARTY

> Unfortunately VS Code doesn't allow us to display SVG (or any other) icons from external source (e.g. REST api or whatever).

That's a shame really.

> I didn't include item's label here because I wanted the TreeView to be clean.

I was imagining the Item label (and type) as part of the context menu (maybe as a topmost disabled menu entry). It's just a minor feature request to provide all info a user might need...

> But I think it's too crowded.

I agree... 🤔  How about this other extreme?

```java
rule "React on ${item.label} (${item.name}) change/update"
when
    Item ${item.name} // your condition here
then
    // your logic here
end
```

> "# This is a combination of 2 commits."

Squashing makes following along changes complicated...

Best! Thomas

**Comment by kubawolanin** [comment]
Hey @ThomDietrich I've added some enhancements to the PR!

> I was imagining the Item label (and type) as part of the context menu (maybe as a topmost disabled menu entry). It's just a minor feature request to provide all info a user might need...

TreeView API doesn't allow you to add disabled menu items too 😟 

> How about this other extreme?

Implemented!

> Squashing makes following along changes complicated...

Yeah. I'll refrain from it 😉Will perform it before merge.

Besides, I've added an **Item completion**:
autocompletion

Will wait a few hours and merge it, if there are no obstacles :-)

**Comment by Confectrician** [comment]
Looks really nice :)

**Comment by ThomDietrich** [comment]
Looks amazing. I'll test all of this later today. This new project really gives a lot to the openHAB world! :beers:

**Pull request merged**
