### PR TITLE
Fix item hover.

### LINKED ISSUE #243: live Item states not working with latest pre-release
After testing `openhab-0.8.1-pr-242-56d7ab7.vsix` and `openhab-0.8.1-pr-242-889d91d.vsix` I realized i do not get live item states anymore.

When I go back to the official release from the market place it works instant.

### PR DESCRIPTION
**Pull request by Confectrician**
Fixes #243

cc: @CWempe  please test, when the build was successful. Thanks in advance.

Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

### CODE REVIEW

**Comment by CWempe** [comment]
Sorry.
I do not know where to download the binary.

Somewhere here, I guess?
https://dev.azure.com/openhab/vscode-openhab/_build/results?buildId=196&view=results

**Comment by Confectrician** [comment]
Ah sorry.
I am already checking if it is possible to make azure post a comment in a PR with a link.

https://artprodsu6weu.artifacts.visualstudio.com/A9a899564-e2b9-49e3-bd3d-4101a64d20ed/82e39b03-2e63-4a34-84ca-3cb57be32202/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL29wZW5oYWIvcHJvamVjdElkLzgyZTM5YjAzLTJlNjMtNGEzNC04NGNhLTNjYjU3YmUzMjIwMi9idWlsZElkLzE5Ni9hcnRpZmFjdE5hbWUvb3BlbmhhYi12c2NvZGU1/content?format=zip

The direct download links are really cryptic to be honest.

https://dev.azure.com/openhab/vscode-openhab/_build/results?buildId=196&view=artifacts&pathAsName=false&type=publishedArtifacts should bring you to the proper place too.

**Comment by CWempe** [comment]
Did a quick test.
Hover for Sleep Time works. 👍 
Hover for Item state works. 👍

**Comment by Confectrician** [comment]
I will give a "Thread sleep generator"-UI a quick try over the weekend.
If i am not satisfied i will push a version 0.8.2 without it to get this included quickly.

**Pull request merged**
