### PR TITLE
[WIP] Initial contribution to i18n

### LINKED ISSUE #55: Support Localization
VSCode has a i18n support.
It would be good to utilize that in the extension as well.

See: https://github.com/vazexqi/vscode-extension-samples/tree/master/i18n-sample

### PR DESCRIPTION
**Pull request by kubawolanin**
Closes #55 

Signed-off-by: Kuba Wolanin <hi@kubawolanin.com>

### CODE REVIEW

**Comment by Confectrician** [comment]
German:
```
{
"openhab.searchDocs.title": "openHAB: In der Dokumentation suchen",
"openhab.searchCommunity.title": "openHAB: Im Community Forum suchen",
"openhab.command.showInPaperUI.title": "In Paper UI anzeigen",
"openhab.command.items.addRule.title": "Regel-Template einfügen",
"openhab.command.items.addToSitemap.title": "In Sitemap einfügen",
"openhab.command.copyName.title": "Namen kopieren",
"openhab.command.items.copyState.title": "Status kopieren",
"openhab.command.things.copyUID.title": "UID kopieren",
"openhab.command.things.addItems.title": "Items aus den Channeln erzeugen",
"openhab.command.things.docs.title": "Binding Dokumentation",
"openhab.command.refreshEntry.title": "Aktualisieren",
"openhab.basicUI.title": "openHAB: Basic UI öffnen",

"openhab.useRestApi.description": "Nutzt die openHAB REST API, wenn die Einstellung aktiviert wurde. Wenn nicht, sind die Baumansicht der Items und code Vervollständigung deaktiviert.",
"openhab.host.description": "Legt die URL oder IP-Adresse von openHAB fest. (Bitte 'localhost' lokaler Nutzung verwenden)",
"openhab.port.description": "Legt den Port von openHAB fest.",
"openhab.lspPort.description": "Legt den von openHAB verwendeten Port für den Language Server fest.",
"openhab.lspEnabled.description": "Aktiviert die Verwendung des Language Server Protocol - Muss in openHAB als 'misc-lsp' add-on installiert sein.",
"openhab.restCompletions.description": "Aktiviert die Vervollständigung durch die REST API",
"openhab.username.description": "Legt den Basic Auth Nutzernamen für den Zugriff auf openHAB fest",
"openhab.password.description": "Legt das Basic Auth Passwort für den Zugriff auf openHAB fest.",
"openhab.paperPath.description": "Diesen Parameter bitte auf 'ui' ändern, wenn ein openHAB2 build von vor dem 9 Januar 2017 verwendet wird.",
"openhab.sitemapPreviewUI.description": "Auswahl welches UI (`basicui` oder `classicui`) für die Sitemap Vorschau im seitlichen Panel verwendet wird.",
"openhab.paperInBrowser.description": "Öffnet über die 'In Paper UI anzeigen' Option eine Ziel-URL in einem externen Browser.",

"openhab.openhabItems.title": "openHAB Items",
"openhab.openhabThings.title": "openHAB Things"
 }
```

Feel free to attach it directly.
Otherwise i will open a PR after yours is merged.
Just wanted to store it already somewhere. 😄

**Comment by ThomDietrich** [comment]
May I suggest to set up https://github.com/marketplace/crowdin for the purpose of adding further translations?

**Comment by kubawolanin** [comment]
Hey @ThomDietrich 👋 
Sure, was thinking about it as well!
Currently I've extracted the labels but there's more of it in the code (e.g. error messages etc).
It'll take some time before it's fully merged but when it's ready I'll definitely incorporate crowdin here.

Cheers

**Comment by ThomDietrich** [comment]
👍 nice. May I ask what is still missing? The PR looks just fine as an initial i18n support

**Comment by kubawolanin** [comment]
I need to reorganize the folder structure and make it actually use that localized strings :-) Right now it uses just English and I didn't have time to push it forward lately.
But we'll get there eventually! ;-)

**Comment by Confectrician** [comment]
Hi all,

Since the android contributors are starting to work with crwodin more and more,
i would like to offer my help here for @kubawolanin.

I am really interested in helping you improving and extending the vscode extension,
but i am just starting with tha typescript stuff and understanding how this works.

But i think i could already start helping you with preparing things for crowdin like the loca strings.
If there's something i can help you with on the folder reorganization that would be fine too.

Wdyt and how can i help you out here?

cc: @ThomDietrich, if i can help you out @ crowdin for vscode already

BR

Jerome

**Comment by ThomDietrich** [comment]
Hey @Confectrician, we are in the process of deploying crowdin for most openHAB projects. Look out for https://crowdin.com/project/openhab-vscode
If you want to help in general you could already join all projects here: https://crowdin.com/projects?q=openhab#advanced-search

@kubawolanin even if the language switching doesn't work yet you could merge the PR so we can go ahead with the translation. This would of course require two things: (1) the basic format and path of the json files is correct and (2) the setup is also able to support regional dialects, e.g. "pt-BR"

**Comment by Confectrician** [comment]
HEy @ThomDietrich,

Yeah i already recognized that empty project and contributed some votes and suggestions to the android translation some minutes ago. 😃

**Comment by Confectrician** [comment]
> Btw @kubawolanin I'm not able to find any useful info regarding "vscode-nls". Could you please refer me to some resource where the whole magic this PR implements is described?

Did you see this link from the original issue?
https://github.com/vazexqi/vscode-extension-samples/tree/master/i18n-sample


Also:
Anything going on here?
If i can already help you with a PR on your fork branch, i would love to do that @kubawolanin.

**Comment by kubawolanin** [comment]
Hi @Confectrician

> Anything going on here?

Sorry, this PR is currently near the bottom of my TODO list. And the list is humongous 😄 
I'd gladly accept the help from you.
I didn't really know how to properly test the translated code yet. (vscode example mentions `process.env.VSCODE_NLS_CONFIG` but I didn't spend much time on it 🙈 )

If you could figure out how to move `package.nls.json`, `package.nls.pl-PL.json` and other translation files (the one you've created too) to `/i18n/` folder and test if it actually works, I think we'd be good to go and merge it already.

After that I think I'd need some small assistance from @ThomDietrich to set up Crowdin properly.
But I hope I'll manage to configure it myself 🤞 

Thank you!

**Comment by ThomDietrich** [comment]
Hey guys,
@Confectrician congrats on the "promotion"! :wink: Way to go!
@kubawolanin the configuration of the crowdin GitHub Integration (through the openhab-bot account) has to happen by Kai. We are talking about how to share hat work but currently it's limited to him.
That means that you just have to prepare the files, Kai can then set up the integration. All you really need to do for that is provide a source file and an idea of the destination file names. Imho we could even do that prior to actually using them! Please remember that crowdin *needs* a source file, you need to provide one even if vscode-nls seems to also be able to live without one...

**Comment by Confectrician** [comment]
Okay i have read through the example but didn't understand it at first read.

But now things get clearer.
What you translated so far are most of the commands and everything that has to be localized in package.json

For "in file loca", we have to use the vscode-nls node package and work with the localize() function.

> Btw. It would be nice to have yet another part of openHAB on crowdin. We are planning a public announcement on localization soon and a big list of already translatable projects would be great then.

I will try to do something her in the next day, but cant promise anything.
How soon is "soon"?

**Comment by ThomDietrich** [comment]
[open-source-project-soon](http://forums.bitminery.com/index.php?action=dlattach;topic=253.0;attach=699) 😉

**Comment by Confectrician** [comment]
Ok i have started from scratch in an own branch now and will add an `also-by:` sign off for your already done part then @kubawolanin.
I just wanted to dig into the process from scratch to understand everything, i think that should be no problem. 😃 

nls seems to work and the variables are taken.

If i do this:
image

It is reflected while debugging:
image

I will now try to implement the folder structure and add (your) polish and german translation and test that.
If it works well, i will file a first initial PR.

**Comment by kubawolanin** [comment]
That's perfect Jerome, thanks!
As for the PR, we can close this one and continue discussion on the new one you'll submit afterwards.
Cheers!

**Comment by kubawolanin** [comment]
PR continued on #89 - closing this one.

**Pull request closed without merging**
