### PR TITLE
Initial snippet file refactoring.

### PR DESCRIPTION
**Pull request by Confectrician**
This is my initial wip attempt for refactoring the snippets area.

As stated in https://github.com/openhab/openhab-vscode/issues/52#issuecomment-346182028 and https://github.com/openhab/openhab-vscode/issues/52#issuecomment-352739559 we agreed in splitting the snippet json files in logical units.

---

My logical idea for starting this is the following:

- openhab.json
for basic stuff like items, things, bridges.
- openhab_rules.json
for basic rule snippets/categories and snippets that don't need an extra file
- openhab_rules_**CATEGORY**.json
for snippet categories with a greater amount of snippets . 
Type conversions is the first logical case for a useful category.
- openhab_sitemaps.json
I think there are more useful snippet cases for sitemaps like Frames or Groups, so there may come additional snippets here. 
Thats why i extracted this already.

---

Of course this is WIP and can be changed.
Since everyone who wants to contribute snippets later needs to be comfortable with this structure,
i wanted to get some opinions and feedback before splitting everything up in several files.
Maybe @kubawolanin had another logical structure in mind, as we discussed about it or maybe this goes in the right direction already. 😃 

---

### You didn't participate in the snippet discussion yet?
No problem. This is not a two man show.
Feel free to add you feedback and opinion or even ideas here.

---
Related: #52, #60, #72
Signed-off-by: Jerome Luckenbach <github@luckenba.ch>

### CODE REVIEW

**Comment by kubawolanin** [comment]
@Confectrician so sorry it took so long for me to finally comment here!
The structure you've proposed makes a lot of sense to me.
I expect the list of snippets to grow up to some point so it's a good idea to have them wisely categorized.
I would propose to have a separate file for design patterns too. What do you think?
I'm aware there are just a couple of them there right now, but it still may grow and it would be easier to manage in the future.

You mentioned it's a WIP - what's left on your plate here? Do you plan to propose some more changes?

Cheers!

**Comment by Confectrician** [comment]
> I would propose to have a separate file for design patterns too. What do you think?
I'm aware there are just a couple of them there right now, but it still may grow and it would be easier to manage in the future.

Fully agree. Additionally it looks like you delivered a huge explanation on some of the design pattern snippets.
So even if the amount of snippets will not be that big, the line count will be anyways.

> You mentioned it's a WIP - what's left on your plate here? Do you plan to propose some more changes?

I mentioned it as WIP, because i mainly wanted to hear your opinion about file structure first.
Currently it looks like you would basically agree with this for now.
So I am fine with doing the design pattern change and merge a first run now.

Wdyt?

**Comment by kubawolanin** [comment]
Absolutely! Thank you 🥂

**Comment by Confectrician** [comment]
I added the change @kubawolanin.

I would ask you to take a short overview again and merge afterwars.
Just because i could merge on my own, i don't want it.
(Especially because it affects somemore files and lines this time.)

Behaviour on my tests was as expected.

**Comment by kubawolanin** [comment]
Looking good @Confectrician, thank you for your work!
I've checked out to your branch and checked everything on my local dev environment.
Works flawlessly!

We're good to merge ;-)

**Pull request merged**
