### PR TITLE
Refactor docs/infos

### LINKED ISSUE #157: Rewrite Readme
Readme has to be adapted to the current changes.

Todo's: 

- [x] Changed folder structure
- [x] Build/Pipeline environment
- [x] Webpack config and usage
- [x] Build workaround for `client/node_modules/copy-paste/index.js` -> Lines 34-36 (openbsd)
- [x] New gifs/screenshots since we have many wrong informations in the existing ones
- [x] Activation events

### PR DESCRIPTION
**Pull request by Confectrician**
Last step needed for the 6.0.0 Milestone.

Maybe @wborn or @kaikreuzer could do me a favor and check if the Contributing page still fits with the organisations policy.
I have already removed an eclipse smarthome reference that i found while editing.

Still to do:
New gifs/screenshots, since the current ones show removed/deprecated commands/features.

Closes #157

### CODE REVIEW

**Comment by wborn** [comment]
Thanks for the update!

The "Discuss your design on the mailing list" part needs to be updated. There isn't any mailing list and the link in that section also doesn't work. For OH2 addons we have a [Discuss your design in the discussion forum](https://github.com/openhab/openhab2-addons/blob/master/CONTRIBUTING.md#discuss-your-design-in-the-discussion-forum) section. But usually these discussions take place in GitHub issues.

I'd also remove the text about "Add your name to the AUTHORS file".

**Comment by wborn** [comment]
The prepare-commit-msg.hook also results in 404 Not Found:

`curl -L -o .git/hooks/prepare-commit-msg https://raw.github.com/openhab/openhab2/master/contrib/prepare-commit-msg.hook && chmod +x .git/hooks/prepare-commit-msg`

**Comment by Confectrician** [comment]
Thanks for checking this @wborn.
I have adressed the comments and removed some stuff.
I also have no idea where the hook template got lost or where it is now, so i removed that one too.

**Comment by Confectrician** [comment]
I had a look at the gifs and we can leave them except one, which i simply removed.
From my view it doesn't add any benefit without the anyways removed functions it explained.

**Pull request merged**
